// Storage facade — Postgres only (RDS / local Docker).
export {
  getBuckets,
  addBucket,
  removeBucket,
  getClassifications,
  saveClassifications,
  updateThreadClassification,
  getLastSortedAt,
  getThreadsCache,
  saveThreadsCache,
  getStoredTokens,
  saveTokens,
  clearTokens,
  deleteAllUserData,
  createJob,
  getActiveJob,
  cancelActiveJobs,
  getJob,
  updateJob,
} from './storage-pg.js'
